////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_CONFIG_PCOUNTER_VIRTUAL_SEQUENCER__SV
`define AHB_CONFIG_PCOUNTER_VIRTUAL_SEQUENCER__SV

class ahb_config_pcounter_virtual_sequencer extends uvm_virtual_sequencer;

    // Register the class ahb_config_pcounter_virtual_sequencer with the factory.
    `uvm_component_utils(ahb_config_pcounter_virtual_sequencer)

    // The Constructor for this Class.
    function new(string name="ahb_config_pcounter_virtual_sequencer", uvm_component parent);
        super.new(name, parent);
    endfunction: new

    // Declare the SubSequencer Handles in this Virtual Sequencer.
    ahb_master_sequencer#(.ADDR_WIDTH(32), .DATA_WIDTH(32)) ahb_master_sequencer_0;

    // Declare the Build Phase of the Virtual Sequencer
    extern virtual function void build_phase(uvm_phase phase);

endclass: ahb_config_pcounter_virtual_sequencer


// Define the Build Phase of the Virtual Sequencer
function void ahb_config_pcounter_virtual_sequencer::build_phase(uvm_phase phase);

    super.build_phase(phase);

    `uvm_info(get_type_name(), "Inside the Build Phase of Virtual Sequencer.", UVM_HIGH)

endfunction: build_phase


`endif