////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_MASTER_AGENT_PKG__SV
`define AHB_MASTER_AGENT_PKG__SV

`include "uvm_macros.svh"

package ahb_master_agent_pkg;

    import uvm_pkg::*;
    import ahb_enum_pkg::*;
    import ahb_master_transaction_pkg::*;

    `include "ahb_master_config.sv"
    `include "ahb_master_driver.sv"
    `include "ahb_master_monitor.sv"
    `include "ahb_master_sequencer.sv"
    `include "ahb_master_agent.sv"
    `include "ahb_reg_adapter.sv"

endpackage : ahb_master_agent_pkg

`endif