////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_ENUM_PKG__SV
`define AHB_ENUM_PKG__SV

package ahb_enum_pkg;
	typedef enum bit	{ AHB_READ=1'b0, AHB_WRITE=1'b1 } 					ahb_read_write_enum;
	typedef enum bit[1:0]	{ AHB_OKAY=2'b00, AHB_ERROR=2'b01, AHB_RETRY=2'b10, AHB_SPLIT=2'b11} ahb_response_type_enum;
endpackage : ahb_enum_pkg

`endif
