////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_CONFIG_PCOUNTER_VIRTUAL_SEQUENCE_LIST__SV
`define AHB_CONFIG_PCOUNTER_VIRTUAL_SEQUENCE_LIST__SV

// Make Forward Declarations of all the Virtual Sequences available in the Library.

typedef class start_counter_vseq;

`endif