////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_WRITE_BASIC_SEQ__SV
`define AHB_WRITE_BASIC_SEQ__SV

class ahb_write_basic_seq#(ADDR_WIDTH=32,DATA_WIDTH=32) extends uvm_sequence#( ahb_master_transaction#(ADDR_WIDTH,DATA_WIDTH) );

    // Register the class ahb_write_basic_seq with the factory.
    `uvm_object_param_utils(ahb_write_basic_seq#(ADDR_WIDTH,DATA_WIDTH))

    rand bit [ADDR_WIDTH-1:0] m_address;

    rand bit [DATA_WIDTH-1:0]  m_wdata;
    

    // The Constructor for this Class.
    function new(string name="ahb_write_basic_seq");
        super.new(name);
    endfunction: new

    // Declare the body of the Sequence
    extern task body();

endclass: ahb_write_basic_seq


task ahb_write_basic_seq::body();

    req = ahb_transaction#(ADDR_WIDTH,DATA_WIDTH)::type_id::create("req");

    //schedule transaction object
    //Fix me: Please Put your logic here

    // Randomize the sequence and start it on the sequencer.
    //Fix me: Please Put your logic here
    if(//randomize the object with constraints)
    begin
        `uvm_fatal(get_type_name(), "[RAND_FAILED]: Randomization failed due to violation of transaction constraints.")
    end

    //finish transaction object schedule
    //Fix me: Please Put your logic here

    // Wait for a Response from the Driver (will be unblocked by put_response(rsp) call).
    //Fix me: Please Put your logic here

endtask : body


`endif
