////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_MASTER_TRANSACTION_PKG__SV
`define AHB_MASTER_TRANSACTION_PKG__SV

`include "uvm_macros.svh"

package ahb_master_transaction_pkg;

    import uvm_pkg::*;
    import ahb_enum_pkg::*;

    `include "ahb_master_transaction.sv"

endpackage : ahb_master_transaction_pkg

`endif