////----------------------------------------------------------------------
//// This file has been automatically generated by
//// VerifStudio Software Version 0.63, Accelver Systems Inc.
//// Any modifications that you make to this file may be
//// overwritten by the tool when regenerating the files. 
////----------------------------------------------------------------------

`ifndef AHB_MASTER_TRANSACTION__SV
`define AHB_MASTER_TRANSACTION__SV

class ahb_master_transaction#(AHB_ADDR_WIDTH=16,AHB_DATA_WIDTH=16) extends uvm_sequence_item;

	// Members
	rand bit [AHB_ADDR_WIDTH-1:0] 		m_address;
	rand ahb_read_write_enum 		m_read_write;
	rand bit [AHB_DATA_WIDTH-1:0]		m_wdata;
	rand bit [AHB_DATA_WIDTH-1:0] 		m_rdata;
	rand ahb_response_type_enum		m_response_type;

    // Register the class ahb_master_transaction with the factory.
    `uvm_object_param_utils_begin(ahb_master_transaction#(AHB_ADDR_WIDTH,AHB_DATA_WIDTH))
		`uvm_field_int	(m_address,									UVM_ALL_ON)
		`uvm_field_int	(m_wdata,									UVM_ALL_ON)
		`uvm_field_int	(m_rdata,									UVM_ALL_ON)
		`uvm_field_enum	(ahb_read_write_enum, m_read_write, 		UVM_ALL_ON)
		`uvm_field_enum	(ahb_response_type_enum, m_response_type, 	UVM_ALL_ON)
    `uvm_object_utils_end

    // The Constructor for this Class.
    function new(string name="ahb_master_transaction");
		super.new(name);
    endfunction: new

	// Constraints
	constraint c_address { m_address >= 0;}

endclass: ahb_master_transaction

`endif
